name: OPT-einsum
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cmake>=3.18
  - ninja                     # Fast CMake builds
  - llvmdev=11                # Required for TVM JIT
  - libffi                    # For TVM's FFI interface
  - gxx_linux-64>=11          # C++17 support
  - numpy
  - psutil
  - cloudpickle
  - xgboost                   # TVM cost model
  - tqdm                      # TVM tuning progress
  - pandas                    # Used indirectly by xgboost/sklearn
  - scikit-learn              # XGBoost backend expects this
  - pip:
      - cython                # Needed to compile TVM Python bindings
      - packaging             # Used in TVM's import logic
      - ml_dtypes             # TVM runtime
      - typing_extensions     # meta_schedule uses Literal[]
      - pyyaml                # Used by Ultralytics and TVM
      - filelock              # Torch, TVM, etc.
      - psutil
